/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BagSVG: typeof import('./src/components/svg/BagSVG.vue')['default']
    CourierSVG: typeof import('./src/components/svg/CourierSVG.vue')['default']
    DetailStatisticOrder: typeof import('./src/components/DetailStatisticOrder.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LogoSVG: typeof import('./src/components/svg/LogoSVG.vue')['default']
    LogoutSVG: typeof import('./src/components/svg/LogoutSVG.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrdersSVG: typeof import('./src/components/svg/OrdersSVG.vue')['default']
    PickerSVG: typeof import('./src/components/svg/PickerSVG.vue')['default']
    ProductItem: typeof import('./src/components/ProductItem.vue')['default']
    ProfileSVG: typeof import('./src/components/svg/ProfileSVG.vue')['default']
    RoleSelector: typeof import('./src/components/RoleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRoleItem: typeof import('./src/components/SelectRoleItem.vue')['default']
    StockSelector: typeof import('./src/components/StockSelector.vue')['default']
    ULoader: typeof import('./src/components/ULoader.vue')['default']
    UserDetailStatistics: typeof import('./src/components/UserDetailStatistics.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
