/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BagSVG: typeof import('./src/components/svg/BagSVG.vue')['default']
    CourierSVG: typeof import('./src/components/svg/CourierSVG.vue')['default']
    LogoSVG: typeof import('./src/components/svg/LogoSVG.vue')['default']
    LogoutSVG: typeof import('./src/components/svg/LogoutSVG.vue')['default']
    OrdersSVG: typeof import('./src/components/svg/OrdersSVG.vue')['default']
    PickerSVG: typeof import('./src/components/svg/PickerSVG.vue')['default']
    ProfileSVG: typeof import('./src/components/svg/ProfileSVG.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRoleItem: typeof import('./src/components/SelectRoleItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSpace: typeof import('vant/es')['Space']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
