/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BagSVG: typeof import('./components/svg/BagSVG.vue')['default']
    CourierSVG: typeof import('./components/svg/CourierSVG.vue')['default']
    DetailStaticticOrder: typeof import('./src/components/DetailStaticticOrder.vue')['default']
    DetailStatisticOrder: typeof import('./components/DetailStatisticOrder.vue')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    LogoSVG: typeof import('./components/svg/LogoSVG.vue')['default']
    LogoutSVG: typeof import('./components/svg/LogoutSVG.vue')['default']
    OrderItem: typeof import('./components/OrderItem.vue')['default']
    OrdersSVG: typeof import('./components/svg/OrdersSVG.vue')['default']
    PickerSVG: typeof import('./components/svg/PickerSVG.vue')['default']
    ProductItem: typeof import('./components/ProductItem.vue')['default']
    ProfileSVG: typeof import('./components/svg/ProfileSVG.vue')['default']
    RoleSelector: typeof import('./components/RoleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRoleItem: typeof import('./components/SelectRoleItem.vue')['default']
    StockSelector: typeof import('./components/StockSelector.vue')['default']
    UserDetailStatistics: typeof import('./components/UserDetailStatistics.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCol: typeof import('vant/es')['Col']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanDivider: typeof import('vant/es')['Divider']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRow: typeof import('vant/es')['Row']
    VanSpace: typeof import('vant/es')['Space']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
